### ISSUE TITLE
thoughts about `WebCAT.utils`

### ISSUE THREAD

**Issue by ebgoldstein** [UNCG-DAISY/PyWebCAT#6]
Ok, @TomasBeuzen so i looked over `webcat_utils` and had a think —

For this project, we might want a single method that does it all.. 

Inputs:
1) camera of interest 
2) a data time (or date-time range) 
3) number of seconds between frame captures (default is 1 frame every 10 seconds… 61 frames for a 10 minute video)
4)  the option to save or delete the raw video (default is trash the video since they are so big)
5) option to write a `.csv`

Outputs:
1) frames saved in a folder called `jpgs`
2) optionally, the video
3) optionally, a `.csv` with some info

the method would do this:
1) from date-time/ date range — generate the URLS needed, using the WebCAT format
2) download each of files from the URLs (`vr.download_url` does this)
3) split the video into frames (at user specified interval) and save frames in a folder called `jpegs` (`vr.save_frames` does this) 
4) optionally delete the video
5) optionally write to a `csv` that has:
	- the file names of each capture, 
	- the date time of the video, 
	- the frame number for the capture, 
	- the Webcat URL (This CSV will be used to join with the labeled data)

**Comment by TomasBeuzen** [comment]
All sounds good. At the moment that functionality is almost there and would kind of work like this:

```
url_list = ["url1", "url2", "url3"]
vr = VidViewer()
for url in url_list:
    vr.fin = url  # set the url
    vr.download_url()  # download if desired (but this is not actually necessary to split into frames)
    vr.save_frames(delta_t=600)  # save frames
    vr.save_metadata()  # this method doesn't exist yet but would save all the metadata of the video in a .csv file
```

I'll specifically note that this class never actually requires you to download the video locally to split it into frames or extract metadata. It reads the video directly from the url into a local session object which is never saved, unless you want to save it by running `vr.download_url()`.

I did originally off-load the url generation into a class attribute, where you could pass in the station/date/time range and the url was generated automatically but it was difficult to catch all the potential errors due to bad inputs and I decided it was better to have the user explicitly pass valid urls to the class instance to download. We can talk more about this tomorrow.

**Comment by ebgoldstein** [comment]
I just wrote a URL generator... I'll upload in just a moment..

**Comment by ebgoldstein** [comment]
i think this can be closed
